# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
- group: assimalign.github

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $MyPat = '$(access.token)'
      $B64Pat = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(":$MyPat"))
      mkdir source
      cd source
      git clone https://github.com/Assimalign-LLC/assimalign-msgraph-utilities.git
      cd assimalign-msgraph-utilities
      git -c http.extraHeader="Authorization: Basic $B64Pat" push --mirror https://assimalign@dev.azure.com/assimalign/Assimalign.1.0/_git/assimalign-msgraph-utilities