name: File Sync

on:
  push:
    branches:
      - main

jobs:
  file_sync:
    runs-on: windows-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            https://assimalign@dev.azure.com/assimalign/Assimalign.1.0/_git/dotnet-packages
          FILES: |
            sync
          TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
